name: edurald
description: A knowledgebase project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  firebase_analytics: ^9.1.10
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.3.0
  firebase_core: ^1.19.2
  cloud_functions: ^3.3.2
#  firebase_functions_interop: ^1.0.2
  firebase_storage: ^10.3.2
  typesense: ^0.2.0
  path_provider: ^2.0.11
  animator: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  expandable: ^5.0.1
  flutter_emoji: ^2.4.0
  #flutter_localized_locales: ^1.1.1
  flutter_gallery_assets: ^1.0.2
  animations: ^2.0.0
  charts_flutter: ^0.12.0
  geolocator: ^7.0.3
  country_codes: 2.2.0
  firebase_database: ^9.0.19
  # geocoder:  0.2.1
  geocoding: ^2.0.4
  fluttertoast: ^8.0.7
  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
  percent_indicator: ^3.0.1
  share: ^2.0.4
  libphonenumber: ^2.0.2
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
#  flutter_country_picker: ^0.1.6
  sliding_up_panel: ^2.0.0+1
#  firebase_messaging: ^10.0.0
  plugin_platform_interface: ^2.0.0
  package_info: ^2.0.2
#  firebase_storage: ^8.1.0
  google_sign_in: ^5.0.4
  linkedin_login: ^2.0.0-dev.4
  image_picker: ^0.8.0+3
  flutter_native_splash: ^2.1.6
  flutter_dotenv: ^5.0.2
  twitter_login: ^4.0.1
  get: ^4.6.5
  flutter_facebook_auth: ^4.4.0+1
  tuple: ^2.0.0
  uuid: 3.0.6
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1

flutter_native_splash:
  image: assets/images/logo.png
#  branding: assets/images/edurald_logo.png
  color: "#ffffff"
  branding_mode: bottom
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner:
  flutter_gen_runner:
  freezed: ^2.1.0+1

flutter_icons:
  android: true
  ios: true

  image_path: assets/images/logo.png
  adaptive_icon_foreground: assets/images/logo.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat Black Italic 900.ttf
          #weight: 900
          #style:  black italic
        - asset: assets/fonts/Montserrat Black 900.ttf
          #weight: 900
          #style: black
        - asset: assets/fonts/Montserrat Bold Italic 700.ttf
          #weight: 700
          #style: Bold Italic
        - asset: assets/fonts/Montserrat Bold 700.ttf
          #weight: 700
          #style: Bold
        - asset: assets/fonts/Montserrat ExtraBold Italic 800.ttf
          #weight: 800
          #style: ExtraBold Italic
        - asset: assets/fonts/Montserrat ExtraBold 800.ttf
          #weight: 800
          #style: ExtraBold
        - asset: assets/fonts/Montserrat ExtraLight Italic 275.ttf
          #weight: 275
          #style: ExtraLight Italic
        - asset: assets/fonts/Montserrat ExtraLight 275.ttf
          #weight: 275
          #style: ExtraLight
        - asset: assets/fonts/Montserrat Italic 400.ttf
          #weight: 400
          #style: Italic
        - asset: assets/fonts/Montserrat Light Italic 300.ttf
          #weight: 300
          #style: Light Italic
        - asset: assets/fonts/Montserrat Light 300.ttf
          #weight: 300
          #style: Light
        - asset: assets/fonts/Montserrat Medium Italic 500.ttf
          #weight: 500
          #style: Medium Italic
        - asset: assets/fonts/Montserrat Medium 500.ttf
          #weight: 500
          #style: Medium
        - asset: assets/fonts/Montserrat Regular 400.ttf
          #weight: 400
          #style: Regular
        - asset: assets/fonts/Montserrat SemiBold 600.ttf
          weight: 600
          #style: semiBold
        - asset: assets/fonts/Montserrat SemiBold 600.ttf
          #weight: 600
          #style: SemiBold
        - asset: assets/fonts/Montserrat Thin Italic 250.ttf
          #weight: 250
          #style: Thin Italic
        - asset: assets/fonts/Montserrat Thin 250.ttf
          #weight: 250
          #style: Thin
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/images/
    - assets/images/socials/
    - assets/json/
  #    - walkthrough1.png
  #    - walkthrough2.png
  #    - walkthrough3.png
  #    - socials.png
  #    - defaultprofile.png
  #    - jolugbo.jpeg
  #    - bg.png
  #    - ph.jpg
  #    - advisory.png
  #    - assetManagement.png
  #    - capitalMarket.png
  #    - trading.jpg
  #    - MA.png
  #    - graduatehat.png
  #    - share1.png
  #    - share2.png
  #    - share3.png
  #    - share4.png
  #    - share5.png
  #    - share6.png
  #    - share7.png
  #    - promoImg.png
  #    - ribbon.jpg
  #    - angella.png
  #    - eniola.png
  #    - welcomelady.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages